version: '3'

services:
  cuda-pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    image: chibachann/cuda-pytorch:12.1-2.2.2-py3.11
    stdin_open: true
    tty: true
    command: /bin/bash
    
    working_dir: /app
    deploy:
      restart_policy:
        condition: none
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

